import './LogoutModal.css';
import './CreateClassModal.css';
import './JoinClassModal.css';
import './SuccessMessageModal.css';
import './DeleteAccountModal.css';
import './SuccessDeleteModal.css';
import './AnswerKeyModal.css';
import './SuccessPublishModal.css';
import './QuestionBankModal.css';